# -*- coding: utf-8 -*-
"""ASSIGNMENTS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tL5gavks_mEt0IcSSg40NrKgwT-BTHYv
"""



"""# 18.01.2021

**Practice 1: Write a pseudocode that reads two numbers and multiplies them together and print out their product:**

INPUT number1 and number2

multiply = number1 * number2

PRINT multiply

**Practice 2: Write a pseudocode that tells a user that the number they entered is not a 5 or a 6.**

INPUT number1

IF number1 = 5

PRINT   “your number is 5”

ELSE IF number1 = 6

PRINT “your number is 6”

ELSE

PRINT “Y our number is not 5 or 6"

**Practice 3: Write a pseudocode to print all multiples of 5 between 0 and 100 (including both 0 and 100).**

SET i=0

For i = 0 To 100

i *=5

Next i

PRINT i

#26.01.2022
**Problem : If you had deposited a coin on the cryptocurrency exchange that brought 7% fixed profit daily for a week, how much would your $ 1000 reach at the end of the 7th day?**
"""

print("WELCOME to Criptocurrency Profit Calculator v.0.0.0.0.0.1 :) \n Type '1' if you want to", end=" ")
print("continue with calculation 1000$ for 7 days with a 7% of fixed daily profit ratio", end="\n")
print(" Type '0' if you want to change the parameters \n")
start_answer=int(input("(1/0 ?) : "))
if start_answer == 1:
  amount=1000
  ratio=0.07
  day=7
  i=1
  for i in range(1,8):
    amount=amount+(amount*ratio)
    amount=round(amount, 2)
    print("Total money at day ",i," : ", amount)
    i+=1
else:
  amount=float(input("Enter the amount of money ($) : "))
  ratio=float(input("Enter the fixed daily profit ratio (0.XX): "))
  day=int(input("Enter the duration of your investment (in days) : "))
  i=1
  for i in range(1,day+1):
    amount=amount+(amount*ratio)
    amount=round(amount, 2)
    print("Total money at day ",i," : ", amount)
    i+=1